services:
  postgres:
    image: postgres:15.4-alpine
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "max_connections=1000"]
    environment:
      POSTGRES_USER: task
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 5
      start_period: 1m

  task-management-migration-db:
    image: task-management-migration-db:latest
    command:
      - "migrate"
      - "apply"
      - "--url"
      - "postgres://task:password@postgres:5432/task?sslmode=disable"
    depends_on:
      postgres:
        condition: service_healthy

  task-management-api:
    image: task-management-api:latest
    ports:
      - "3000:3000"
    environment:
      DB_CONNECTION_STRING: postgres://task:password@postgres:5432/task
      CONFIG_FILE: /config/$ENV/api.yaml
      OPEN_API_FILE_PATH: /openapi/openapi.yaml
    env_file:
      - ./secrets/$ENV.env
    depends_on:
      task-management-migration-db:
        condition: service_completed_successfully

  task-management-api-docs:
    image: task-management-api-docs:latest
    ports:
      - "3001:3001"

volumes:
  postgres:
